# SPRITES 
require "gosu";
$VIKING_IDLE = Gosu::Image.new("img/enemies/viking.bmp",{retro:true});
$VIKING_WALKING1 = Gosu::Image.new("img/enemies/viking_5.bmp",{retro:true});
$VIKING_WALKING2 = Gosu::Image.new("img/enemies/viking_2.bmp",{retro:true});
$VIKING_WALKING3 = Gosu::Image.new("img/enemies/viking_3.bmp",{retro:true});
$VIKING_WALKING4 = Gosu::Image.new("img/enemies/viking_3_5.bmp",{retro:true});
$ROCK_SPRITE = Gosu::Image.new("img/terrain_objects/rock.bmp",{retro:true});
$GOLD_SACK_SPRITE = Gosu::Image.new("img/items/gold_sack.bmp",{retro:true});
$HEALTH_POTION_SPRITE = Gosu::Image.new("img/items/potion.bmp",{retro:true});
$MANA_POTION_SPRITE = Gosu::Image.new("img/items/mana_potion.bmp",{retro:true});
$OGRE_IDLE = Gosu::Image.new("img/enemies/ogre.bmp",{retro:true});
$OGRE_WALKING1 = Gosu::Image.new("img/enemies/ogre_5.bmp",{retro:true});
$OGRE_WALKING2 = Gosu::Image.new("img/enemies/ogre_2.bmp",{retro:true});
$OGRE_WALKING3 = Gosu::Image.new("img/enemies/ogre_3.bmp",{retro:true});
$DEMON_IDLE = Gosu::Image.new("img/enemies/demon.bmp",{retro:true});
$DEMON_WALKING1 = Gosu::Image.new("img/enemies/demon_5.bmp",{retro:true});
$DEMON_WALKING2 = Gosu::Image.new("img/enemies/demon_2.bmp",{retro:true});
$DEMON_WALKING3 = Gosu::Image.new("img/enemies/demon_2_5.bmp",{retro:true});
$ATTACK_ANIMATION1 = Gosu::Image.new("img/animations/attack_1.bmp",{retro:true});
$ATTACK_ANIMATION2 = Gosu::Image.new("img/animations/attack_2.bmp",{retro:true});
$ATTACK_ANIMATION3 = Gosu::Image.new("img/animations/attack_3.bmp",{retro:true});
$ATTACK_ANIMATION4 = Gosu::Image.new("img/animations/attack_4.bmp",{retro:true});
$ATTACK_ANIMATION5 = Gosu::Image.new("img/animations/attack_5.bmp",{retro:true});